language: node_js
node_js:
    - '4.4'

addons:
  sauce_connect: true

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

before_script:
    - npm install
    - npm install angular-cli
    - webdriver-manager update

script:
    - ng test --watch=false
    - ng serve
    - ng e2e
